(function(){
'use strict';var WF=function(a){for(var b=Array(arguments.length),c=0;;)if(c<b.length)b[c]=arguments[c],c+=1;else return b},XF=function(a){a=a.destroy;return null==a?null:a.m?a.m():a.call(null)},YF=function(a){$APP.ki(a,$APP.Na());$APP.m($APP.Oa)&&$APP.li($APP.Na())},ZF=function(){var a=$APP.Pj;return null==a?[]:$APP.ak(WF,a,$APP.Aw,null,XF)},$F=function(a,b,c,d,e){var f=$APP.xl($APP.u(c)),g=$APP.xl($APP.u(c)),h=$APP.ra(e);return function(n,p,q,t,w){$APP.Ve($APP.u(g),$APP.u(q))&&($APP.pf(f,$APP.u(q)),
$APP.pf(g,$APP.u(q)));return new $APP.V(null,2,5,$APP.W,[n,$APP.X.j(p,$APP.Bx,function(){var y=$APP.u(f);return t.g?t.g(y):t.call(null,y)}(),$APP.J([$APP.Lu,function(y){y=y.target.value;h.h?h.h(q,y):h.call(null,q,y);return w.h?w.h(f,y):w.call(null,f,y)}]))],null)}},aG=function(a,b,c){for(var d=0,e=$APP.H(a);;)if(d<e){var f=$APP.le(d+e,2);var g=$APP.O.h(a,f);g=c.g?c.g(g):c.call(null,g);0>$APP.Sd(g,b)?d=f+1:e=f}else return d},bG=function(a,b,c){return $APP.Wf($APP.zf.j($APP.cg(a,0,b),new $APP.V(null,
1,5,$APP.W,[c],null),$APP.J([$APP.cg(a,b,$APP.H(a))])))},cG=function(a,b){return $APP.Wf($APP.zf.h($APP.cg(a,0,b),$APP.cg(a,b+1,$APP.H(a))))},dG=function(a,b){function c(g){return $APP.cg(g,0,2)}a=$APP.Wf(a);var d=c(b),e=aG(a,d,c),f=$APP.O.h(a,e);return $APP.Jd(f)&&$APP.I.h(d,c(f))?$APP.X.i(a,e,b):bG(a,e,b)},eG=function(a,b){function c(f){return $APP.cg(f,0,2)}a=$APP.Wf(a);b=c(b);var d=aG(a,b,c),e=$APP.O.h(a,d);return $APP.Jd(e)&&$APP.I.h(b,c(e))?cG(a,d):a},fG=function(a,b){function c(e){return $APP.cg(e,
0,2)}a=$APP.Wf(a);b=c(b);var d=aG(a,b,c);a=$APP.O.h(a,d);return $APP.Jd(a)&&$APP.I.h(b,c(a))},gG=function(a){var b=ZF(),c=0===b.length,d=c||$APP.Ta(b.hasOwnProperty(0))?b[0]=$APP.xl(!1):b[0],e=c||$APP.Ta(b.hasOwnProperty(1))?b[1]=$APP.of(null):b[1],f=c||$APP.Ta(b.hasOwnProperty(2))?b[2]=function(){return $APP.pf(d,!0)}:b[2];return $APP.m(function(){var g=$APP.u(d);return $APP.m(g)?g:$APP.Cd($APP.u(a))}())?new $APP.V(null,3,5,$APP.W,[$APP.qw,new $APP.l(null,1,[$APP.Ew,function(g){console.log(g);g.preventDefault();
$APP.pf(a,g.target.elements.namefield.value);return $APP.pf(d,!1)}],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,5,[$APP.Hv,$APP.Cw,$APP.tj,"namefield",$APP.Kw,!0,$APP.uv,$APP.u(a),$APP.Fx,function(g){$APP.pf(a,g.target.value);return $APP.pf(d,!1)}],null)],null)],null):new $APP.V(null,3,5,$APP.W,[$APP.Lv,new $APP.l(null,1,[$APP.Yu,function(g){return $APP.I.h(g.detail,1)?$APP.pf(e,window.setTimeout(f,1E3)):window.clearTimeout($APP.u(e))}],null),$APP.u(a)],null)},jG=function(){return new $APP.V(null,
3,5,$APP.W,[hG,new $APP.l(null,1,[$APP.pl,$APP.m($APP.u(iG))?"visible":"hidden"],null),$APP.u(iG)],null)},pG=function(){var a=$APP.u(kG),b=$APP.Ue(a);a=$APP.O.h(b,$APP.tx);var c=$APP.O.h(b,$APP.sx);b=$APP.O.h(b,lG);return new $APP.V(null,3,5,$APP.W,[mG,new $APP.l(null,2,[$APP.Iv,new $APP.l(null,2,[nG,c,oG,a],null),$APP.pl,$APP.m(b)?"visible":"hidden"],null),b],null)},rG=function(a,b){return $APP.pf(iG,new $APP.V(null,6,5,$APP.W,[$APP.qw,new $APP.l(null,1,[$APP.Ew,function(c){console.log(c);c.preventDefault();
c=c.target.elements.valuefield.value;$APP.D(c)&&(b.g?b.g(c):b.call(null,c));return $APP.pf(iG,null)}],null),new $APP.V(null,2,5,$APP.W,[qG,a],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.tj,"valuefield",$APP.Hv,"text",$APP.Kw,!0],null)],null),new $APP.V(null,3,5,$APP.W,[$APP.Lw,new $APP.l(null,1,[$APP.Yu,function(){return $APP.pf(iG,null)}],null),"Cancel"],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,2,[$APP.Hv,"submit",$APP.Bx,"Ok"],null)],null)],null))},sG=function(a){return $APP.pf(iG,
new $APP.V(null,3,5,$APP.W,[qG,new $APP.V(null,2,5,$APP.W,[$APP.xx,a],null),new $APP.V(null,3,5,$APP.W,[$APP.Lw,new $APP.l(null,1,[$APP.Yu,function(){return $APP.pf(iG,null)}],null),"Ok"],null)],null))},wG=function(a,b){a.preventDefault();return $APP.pf(kG,new $APP.l(null,3,[$APP.tx,a.clientX,$APP.sx,a.clientY,lG,new $APP.V(null,2,5,$APP.W,[tG,new $APP.V(null,3,5,$APP.W,[uG,new $APP.l(null,1,[$APP.Yu,function(){return $APP.Y.i(vG,$APP.Tj,b)}],null),"delete"],null)],null)],null))},xG=function(a,b){var c=
$APP.I,d=c.h,e=$APP.H(a),f=$APP.H(b);return d.call(c,$APP.cg(a,0,e<f?e:f),b)},zG=function(a){return $APP.sf.h(function(b){return $APP.ue.h($APP.nj(b,"/"),$APP.Fm.g(a))},$APP.ue.h($APP.Af(yG,$APP.J([$APP.vh($APP.zy.g(a))])),"Everything"))},AG=function(){var a=$APP.u(vG);return $APP.$a(function(b,c){return $APP.ou(b,c,$APP.U)},$APP.U,$APP.Af(zG,$APP.J([$APP.vh(a)])))},EG=function(){return new $APP.V(null,2,5,$APP.W,[BG,$APP.D($APP.u(vG))?new $APP.V(null,3,5,$APP.W,[CG,$APP.Vf,AG()],null):new $APP.V(null,
2,5,$APP.W,[DG,'There aren\'t any interfaces yet. Open a different workspace or click "Add interface" to get started.'],null)],null)},HG=function(a,b){a=[$APP.r.g(a),"$",$APP.r.g(b)].join("");b=new URL("editor",window.location);b.searchParams.append("schem",a);b.searchParams.append("db",FG);b.searchParams.append("sync",GG);return b},JG=function(a,b,c,d){a.preventDefault();return $APP.pf(kG,new $APP.l(null,3,[$APP.tx,a.clientX,$APP.sx,a.clientY,lG,new $APP.V(null,3,5,$APP.W,[tG,new $APP.V(null,3,5,
$APP.W,[uG,new $APP.l(null,1,[$APP.Yu,function(){return window.open(HG($APP.td(c.split(":")),$APP.Jh(d)),c)}],null),"edit"],null),new $APP.V(null,3,5,$APP.W,[uG,new $APP.l(null,1,[$APP.Yu,function(){return $APP.Y.j(b,IG,new $APP.V(null,2,5,$APP.W,[c,$APP.zy],null),$APP.Tj,$APP.J([d]))}],null),"delete"],null)],null)],null))},OG=function(a){var b=$APP.u(KG),c=$APP.O.h($APP.u(a),b);return new $APP.V(null,2,5,$APP.W,[LG,$APP.m($APP.u(KG))?new $APP.V(null,5,5,$APP.W,[$APP.SA,MG,$APP.Sh(function(){return function f(e){return new $APP.Ce(null,
function(){for(var g=e;;)if(g=$APP.D(g)){if($APP.Kd(g)){var h=$APP.uc(g),n=$APP.H(h),p=$APP.Fe(n);return function(){for(var y=0;;)if(y<n){var A=$APP.wd(h,y),B=$APP.N(A,0,null);A=$APP.N(A,1,null);var G=(G=$APP.I.h($APP.u(NG),new $APP.V(null,1,5,$APP.W,["Everything"],null)))?G:$APP.gf($APP.jo.h($APP.I,$APP.S.h($APP.r,$APP.yf("/",$APP.u(NG)))),yG.g(A));$APP.m(G)&&(G=$APP.I.h($APP.Df(c,new $APP.V(null,3,5,$APP.W,[$APP.zy,B,$APP.Hv],null)),"schematic")?$APP.KA:$APP.JA,B=new $APP.V(null,4,5,$APP.W,[new $APP.V(null,
4,5,$APP.W,[$APP.Lv,new $APP.V(null,1,5,$APP.W,[G],null)," ",$APP.O.i(A,$APP.tj,B)],null),new $APP.V(null,4,5,$APP.W,[$APP.Lv,new $APP.V(null,1,5,$APP.W,[G],null)," ",new $APP.V(null,2,5,$APP.W,[gG,$APP.yl(a,new $APP.V(null,4,5,$APP.W,[b,$APP.zy,B,$APP.tj],null))],null)],null),B,B],null),p.add(B));y+=1}else return!0}()?$APP.Ie($APP.Ke(p),f($APP.vc(g))):$APP.Ie($APP.Ke(p),null)}var q=$APP.E(g),t=$APP.N(q,0,null),w=$APP.N(q,1,null);if($APP.m(function(){var y=$APP.I.h($APP.u(NG),new $APP.V(null,1,5,
$APP.W,["Everything"],null));return y?y:$APP.gf($APP.jo.h($APP.I,$APP.S.h($APP.r,$APP.yf("/",$APP.u(NG)))),yG.g(w))}()))return q=$APP.I.h($APP.Df(c,new $APP.V(null,3,5,$APP.W,[$APP.zy,t,$APP.Hv],null)),"schematic")?$APP.KA:$APP.JA,$APP.xe(new $APP.V(null,4,5,$APP.W,[new $APP.V(null,4,5,$APP.W,[$APP.Lv,new $APP.V(null,1,5,$APP.W,[q],null)," ",$APP.O.i(w,$APP.tj,t)],null),new $APP.V(null,4,5,$APP.W,[$APP.Lv,new $APP.V(null,1,5,$APP.W,[q],null)," ",new $APP.V(null,2,5,$APP.W,[gG,$APP.yl(a,new $APP.V(null,
4,5,$APP.W,[b,$APP.zy,t,$APP.tj],null))],null)],null),t,t],null),f($APP.Uc(g)));g=$APP.Uc(g)}else return null},null,null)}($APP.zy.g(c))}()),function(d){return $APP.I.h($APP.Df(c,new $APP.V(null,3,5,$APP.W,[$APP.zy,d,$APP.Hv],null)),"schematic")?function(){return window.open(HG($APP.td(b.split(":")),$APP.Jh(d)),b)}:null},function(d){return function(e){return JG(e,a,b,d)}}],null):new $APP.V(null,2,5,$APP.W,[DG,"There are no implementations to show. Select an interface to edit its schematics and SPICE models."],
null)],null)},SG=function(){return new $APP.V(null,2,5,$APP.W,[PG,new $APP.V(null,3,5,$APP.W,[$APP.Gx,new $APP.V(null,2,5,$APP.W,[$APP.vw,"Workspace properties"],null),new $APP.V(null,6,5,$APP.W,[QG,new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,1,[$APP.zv,"dbname"],null),"Name"],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.rl,"dbname",$APP.tj,"db",$APP.uv,FG],null)],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,1,[$APP.zv,"dbsync"],null),"URL"],null),new $APP.V(null,
2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.rl,"dbsync",$APP.tj,"sync",$APP.uv,GG],null)],null),new $APP.V(null,4,5,$APP.W,[RG,new $APP.l(null,1,[$APP.Hv,"submit"],null),new $APP.V(null,1,5,$APP.W,[$APP.LA],null),"Open"],null)],null)],null)],null)},XG=function(a){var b=$APP.Zx.g($APP.u(a)),c=$APP.N(b,0,null),d=$APP.N(b,1,null),e=2+c,f=2+d;return new $APP.V(null,2,5,$APP.W,[TG,new $APP.V(null,2,5,$APP.W,[UG,$APP.Sh(function(){return function n(h){return new $APP.Ce(null,function(){for(;;){var p=$APP.D(h);
if(p){var q=p;if($APP.Kd(q)){var t=$APP.uc(q),w=$APP.H(t),y=$APP.Fe(w);return function(){for(var B=0;;)if(B<w){var G=$APP.wd(t,B);$APP.Je(y,new $APP.V(null,3,5,$APP.W,[VG,new $APP.l(null,1,[$APP.wj,G],null),$APP.Sh(function(){return function(K,M,Q,T,ba,Z,ca,sa,aa,da,ha,ka){return function Bb(La){return new $APP.Ce(null,function(oc,Gb,pc,ce,dd,Tb,Ae,qd,ac,Qc,Hd,Ub){return function(){for(;;){var hc=$APP.D(La);if(hc){var Rc=hc;if($APP.Kd(Rc)){var Ye=$APP.uc(Rc),zj=$APP.H(Ye),zh=$APP.Fe(zj);return function(){for(var Ah=
0;;)if(Ah<zj){var yg=$APP.wd(Ye,Ah),Aj=function(Bj,Cj,gc,fy,gy,hy,jp,bj,Zg){return function(fg){return $APP.m(fg.target.checked)?$APP.Y.j(a,$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,3,5,$APP.W,[gc,Zg,"#"],null)])):$APP.Y.j(a,$APP.pu,$APP.Ev,eG,$APP.J([new $APP.V(null,3,5,$APP.W,[gc,Zg,"#"],null)]))}}(Ah,oc,yg,Ye,zj,zh,Rc,hc,Gb,pc,ce,dd,Tb,Ae,qd,ac,Qc,Hd,Ub);$APP.Je(zh,new $APP.V(null,3,5,$APP.W,[WG,new $APP.l(null,1,[$APP.wj,yg],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.Hv,
"checkbox",$APP.Zw,fG($APP.Ev.g($APP.u(a)),new $APP.V(null,2,5,$APP.W,[yg,Gb],null)),$APP.Lu,Aj],null)],null)],null));Ah+=1}else return!0}()?$APP.Ie($APP.Ke(zh),Bb($APP.vc(Rc))):$APP.Ie($APP.Ke(zh),null)}var Ze=$APP.E(Rc),Hk=function(Ah,yg,Aj,Bj,Cj){return function(gc){return $APP.m(gc.target.checked)?$APP.Y.j(a,$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,3,5,$APP.W,[yg,Cj,"#"],null)])):$APP.Y.j(a,$APP.pu,$APP.Ev,eG,$APP.J([new $APP.V(null,3,5,$APP.W,[yg,Cj,"#"],null)]))}}(oc,Ze,Rc,hc,Gb,pc,ce,dd,
Tb,Ae,qd,ac,Qc,Hd,Ub);return $APP.xe(new $APP.V(null,3,5,$APP.W,[WG,new $APP.l(null,1,[$APP.wj,Ze],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.Hv,"checkbox",$APP.Zw,fG($APP.Ev.g($APP.u(a)),new $APP.V(null,2,5,$APP.W,[Ze,Gb],null)),$APP.Lu,Hk],null)],null)],null),Bb($APP.Uc(Rc)))}return null}}}(K,M,Q,T,ba,Z,ca,sa,aa,da,ha,ka),null,null)}}(B,G,t,w,y,q,p,b,c,d,e,f)($APP.Qh(0,e))}())],null));B+=1}else return!0}()?$APP.Ie($APP.Ke(y),n($APP.vc(q))):$APP.Ie($APP.Ke(y),null)}var A=$APP.E(q);
return $APP.xe(new $APP.V(null,3,5,$APP.W,[VG,new $APP.l(null,1,[$APP.wj,A],null),$APP.Sh(function(){return function(B,G,K,M,Q,T,ba,Z){return function aa(sa){return new $APP.Ce(null,function(){for(;;){var da=$APP.D(sa);if(da){var ha=da;if($APP.Kd(ha)){var ka=$APP.uc(ha),ma=$APP.H(ka),La=$APP.Fe(ma);return function(){for(var Gb=0;;)if(Gb<ma){var pc=$APP.wd(ka,Gb),ce=function(dd,Tb,Ae,qd,ac,Qc,Hd,Ub){return function(hc){return $APP.m(hc.target.checked)?$APP.Y.j(a,$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,
3,5,$APP.W,[Tb,Ub,"#"],null)])):$APP.Y.j(a,$APP.pu,$APP.Ev,eG,$APP.J([new $APP.V(null,3,5,$APP.W,[Tb,Ub,"#"],null)]))}}(Gb,pc,ka,ma,La,ha,da,B,G,K,M,Q,T,ba,Z);$APP.Je(La,new $APP.V(null,3,5,$APP.W,[WG,new $APP.l(null,1,[$APP.wj,pc],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.Hv,"checkbox",$APP.Zw,fG($APP.Ev.g($APP.u(a)),new $APP.V(null,2,5,$APP.W,[pc,B],null)),$APP.Lu,ce],null)],null)],null));Gb+=1}else return!0}()?$APP.Ie($APP.Ke(La),aa($APP.vc(ha))):$APP.Ie($APP.Ke(La),null)}var Bb=
$APP.E(ha),oc=function(Gb,pc,ce,dd){return function(Tb){return $APP.m(Tb.target.checked)?$APP.Y.j(a,$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,3,5,$APP.W,[Gb,dd,"#"],null)])):$APP.Y.j(a,$APP.pu,$APP.Ev,eG,$APP.J([new $APP.V(null,3,5,$APP.W,[Gb,dd,"#"],null)]))}}(Bb,ha,da,B,G,K,M,Q,T,ba,Z);return $APP.xe(new $APP.V(null,3,5,$APP.W,[WG,new $APP.l(null,1,[$APP.wj,Bb],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,3,[$APP.Hv,"checkbox",$APP.Zw,fG($APP.Ev.g($APP.u(a)),new $APP.V(null,2,5,$APP.W,
[Bb,B],null)),$APP.Lu,oc],null)],null)],null),aa($APP.Uc(ha)))}return null}},null,null)}}(A,q,p,b,c,d,e,f)($APP.Qh(0,e))}())],null),n($APP.Uc(q)))}return null}},null,null)}($APP.Qh(0,f))}())],null)],null)},YG=function(a){return new $APP.V(null,5,5,$APP.W,[$APP.lv,new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"bgwidth",$APP.Yv,"Width of the background tile"],null),"Background width"],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,4,[$APP.rl,"bgwidth",$APP.Hv,"number",$APP.uv,
$APP.O.i($APP.Zx.g($APP.u(a)),0,1),$APP.Lu,$APP.ra(function(b){return $APP.Y.j(a,$APP.pu,$APP.Zx,$APP.kf($APP.X,new $APP.V(null,2,5,$APP.W,[0,0],null)),$APP.J([0,parseInt(b.target.value)]))})],null)],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"bgheight",$APP.Yv,"Width of the background tile"],null),"Background height"],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,4,[$APP.rl,"bgheigt",$APP.Hv,"number",$APP.uv,$APP.O.i($APP.Zx.g($APP.u(a)),1,1),$APP.Lu,$APP.ra(function(b){return $APP.Y.j(a,
$APP.pu,$APP.Zx,$APP.kf($APP.X,new $APP.V(null,2,5,$APP.W,[0,0],null)),$APP.J([1,parseInt(b.target.value)]))})],null)],null)],null)},ZG=function(a){return new $APP.V(null,2,5,$APP.W,[$APP.lv,function(){return function d(c){return new $APP.Ce(null,function(){for(;;){var e=$APP.D(c);if(e){var f=e;if($APP.Kd(f)){var g=$APP.uc(f),h=$APP.H(g),n=$APP.Fe(h);return function(){for(var y=0;;)if(y<h){var A=$APP.wd(g,y),B=$APP.N(A,0,null),G=$APP.N(A,1,null),K=$APP.N(A,2,null);A=$APP.ra(function(M,Q,T,ba){return function(Z){return $APP.Y.j(a,
$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,3,5,$APP.W,[T,ba,Z.target.value],null)]))}}(y,A,B,G,K,g,h,n,f,e));$APP.Je(n,new $APP.V(null,4,5,$APP.W,[$APP.lv,new $APP.l(null,1,[$APP.wj,new $APP.V(null,2,5,$APP.W,[B,G],null)],null),new $APP.V(null,5,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,["port",$APP.r.g(B),":",$APP.r.g(G)].join(""),$APP.Yv,"Port name"],null),B,"/",G],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,4,[$APP.rl,["port",$APP.r.g(B),":",$APP.r.g(G)].join(""),$APP.Hv,"text",
$APP.uv,K,$APP.Lu,A],null)],null)],null));y+=1}else return!0}()?$APP.Ie($APP.Ke(n),d($APP.vc(f))):$APP.Ie($APP.Ke(n),null)}var p=$APP.E(f),q=$APP.N(p,0,null),t=$APP.N(p,1,null),w=$APP.N(p,2,null);p=$APP.ra(function(y,A,B){return function(G){return $APP.Y.j(a,$APP.pu,$APP.Ev,dG,$APP.J([new $APP.V(null,3,5,$APP.W,[A,B,G.target.value],null)]))}}(p,q,t,w,f,e));return $APP.xe(new $APP.V(null,4,5,$APP.W,[$APP.lv,new $APP.l(null,1,[$APP.wj,new $APP.V(null,2,5,$APP.W,[q,t],null)],null),new $APP.V(null,5,
5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,["port",$APP.r.g(q),":",$APP.r.g(t)].join(""),$APP.Yv,"Port name"],null),q,"/",t],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,4,[$APP.rl,["port",$APP.r.g(q),":",$APP.r.g(t)].join(""),$APP.Hv,"text",$APP.uv,w,$APP.Lu,p],null)],null)],null),d($APP.Uc(f)))}return null}},null,null)}($APP.Ev.g($APP.u(a)))}()],null)},$G=function(a){var b=$APP.u(KG),c=$APP.yl(a,new $APP.V(null,1,5,$APP.W,[b],null));return $APP.m(b)?new $APP.V(null,2,5,$APP.W,[$APP.lv,
new $APP.V(null,7,5,$APP.W,[$APP.Su,new $APP.V(null,2,5,$APP.W,[YG,c],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"ports",$APP.Yv,"pattern for the device ports"],null),"ports"],null),new $APP.V(null,2,5,$APP.W,[XG,c],null),new $APP.V(null,2,5,$APP.W,[ZG,c],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"symurl",$APP.Yv,"image url for this component"],null),"url"],null),new $APP.V(null,2,5,$APP.W,[$APP.Vw,new $APP.l(null,4,[$APP.rl,"symurl",$APP.Hv,"text",
$APP.uv,$APP.Df($APP.u(a),new $APP.V(null,2,5,$APP.W,[b,$APP.Gy],null)),$APP.Fx,function(d){return $APP.Y.s(a,$APP.ou,new $APP.V(null,2,5,$APP.W,[b,$APP.Gy],null),d.target.value)}],null)],null)],null)],null):new $APP.V(null,2,5,$APP.W,[DG,"Select an interface to edit its properties."],null)},gH=function(a){var b=$APP.yl(a,new $APP.V(null,4,5,$APP.W,[$APP.u(KG),$APP.zy,$APP.ei.g($APP.u(MG)),$APP.ei.g($APP.u(aH))],null));YF($APP.J([$APP.u(b)]));return new $APP.V(null,3,5,$APP.W,[$APP.Su,$APP.I.h($APP.Df($APP.u(a),
new $APP.V(null,4,5,$APP.W,[$APP.u(KG),$APP.zy,$APP.ei.g($APP.u(MG)),$APP.Hv],null)),"spice")?new $APP.V(null,10,5,$APP.W,[$APP.lv,new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,1,[$APP.zv,"dialect"],null),"Simulator"],null),new $APP.V(null,4,5,$APP.W,[$APP.cw,new $APP.l(null,4,[$APP.rl,"dialect",$APP.Hv,"text",$APP.Bx,$APP.u(aH),$APP.Lu,function(c){return $APP.pf(aH,c.target.value)}],null),new $APP.V(null,2,5,$APP.W,[$APP.Bv,"NgSpice"],null),new $APP.V(null,2,5,$APP.W,[$APP.Bv,"Xyce"],null)],
null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,1,[$APP.zv,"reftempl"],null),"Reference template"],null),new $APP.V(null,6,5,$APP.W,[$F,$APP.py,new $APP.l(null,2,[$APP.rl,"reftempl",bH,"X{name} {ports} {properties}"],null),b,cH,function(c,d){return $APP.Y.s(c,$APP.X,cH,d)}],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,1,[$APP.zv,"decltempl"],null),"Declaration template"],null),new $APP.V(null,6,5,$APP.W,[$F,$APP.py,new $APP.l(null,1,[$APP.rl,"decltempl"],null),b,dH,function(c,
d){return $APP.Y.s(c,$APP.X,dH,d)}],null),new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"vectors",$APP.Yv,"Comma-seperated device outputs to save"],null),"Vectors"],null),new $APP.V(null,6,5,$APP.W,[$F,$APP.Vw,new $APP.l(null,2,[$APP.rl,"vectors",bH,"id, gm"],null),b,function(c){return $APP.S.h($APP.r,$APP.yf(", ",eH.g(c)))},function(c,d){return $APP.Y.s(c,$APP.X,eH,$APP.mj(d,/, /,-1))}],null),0==cH.h($APP.u(b),"").toLowerCase().lastIndexOf("x",0)?new $APP.V(null,3,5,$APP.W,[$APP.lv,
new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"vectorcomp",$APP.Yv,"For subcircuits, the name of the thing inside of which to save vectors"],null),"Main component"],null),new $APP.V(null,6,5,$APP.W,[$F,$APP.Vw,new $APP.l(null,1,[$APP.rl,"vectorcomp"],null),b,fH,function(c,d){return $APP.Y.s(c,$APP.X,fH,d)}],null)],null):null],null):$APP.m(function(){var c=$APP.u(KG);return $APP.m(c)?$APP.u(MG):c}())?new $APP.V(null,2,5,$APP.W,[$APP.lv,new $APP.V(null,3,5,$APP.W,[$APP.rx,new $APP.l(null,
2,[$APP.Fv,HG($APP.td($APP.u(KG).split(":")),$APP.Jh($APP.u(MG))),$APP.$u,$APP.u(KG)],null),"Edit"],null)],null):null,$APP.m(function(){var c=$APP.u(KG);return $APP.m(c)?$APP.u(MG):c}())?new $APP.V(null,3,5,$APP.W,[$APP.lv,new $APP.V(null,3,5,$APP.W,[$APP.Xw,new $APP.l(null,2,[$APP.zv,"categories",$APP.Yv,"Comma-seperated device categories"],null),"Categories"],null),new $APP.V(null,6,5,$APP.W,[$F,$APP.Vw,new $APP.l(null,1,[$APP.rl,"categories"],null),b,function(c){return $APP.S.h($APP.r,$APP.yf(", ",
yG.g(c)))},function(c,d){return $APP.Y.s(c,$APP.X,yG,$APP.mj(d,/, /,-1))}],null)],null):new $APP.V(null,2,5,$APP.W,[DG,"Select a schematic or SPICE model to edit its properties."],null)],null)},qH=function(){return new $APP.V(null,3,5,$APP.W,[$APP.lv,new $APP.V(null,4,5,$APP.W,[hH,new $APP.V(null,3,5,$APP.W,[iH,new $APP.V(null,4,5,$APP.W,[$APP.Lw,new $APP.l(null,2,[$APP.Yu,function(){return rG("Enter the name of the new interface",function(a){return $APP.Y.s(vG,$APP.X,["models:",$APP.r.g(a)].join(""),
new $APP.l(null,1,[$APP.tj,a],null))})},jH,null==$APP.u(NG)],null),new $APP.V(null,1,5,$APP.W,[$APP.NA],null),"Add interface"],null),new $APP.V(null,3,5,$APP.W,[kH,new $APP.V(null,4,5,$APP.W,[$APP.Lw,new $APP.l(null,2,[$APP.Yu,function(){return rG("Enter the name of the new schematic",function(a){return $APP.Y.s(vG,$APP.ou,new $APP.V(null,3,5,$APP.W,[$APP.u(KG),$APP.zy,$APP.ei.g(a)],null),new $APP.l(null,2,[$APP.tj,a,$APP.Hv,"schematic"],null))})},jH,null==$APP.u(NG)||null==$APP.u(KG)],null),new $APP.V(null,
1,5,$APP.W,[$APP.MA],null),"Add schematic"],null),new $APP.V(null,3,5,$APP.W,[$APP.Gx,new $APP.V(null,1,5,$APP.W,[lH],null),new $APP.V(null,4,5,$APP.W,[$APP.Lw,new $APP.l(null,2,[$APP.Yu,function(){return rG("Enter the name of the new SPICE model",function(a){return $APP.Y.s(vG,$APP.ou,new $APP.V(null,3,5,$APP.W,[$APP.u(KG),$APP.zy,$APP.ei.g(a)],null),new $APP.l(null,2,[$APP.tj,a,$APP.Hv,"spice"],null))})},jH,null==$APP.u(NG)||null==$APP.u(KG)],null),new $APP.V(null,1,5,$APP.W,[$APP.MA],null),"Add SPICE model"],
null)],null)],null)],null),new $APP.V(null,3,5,$APP.W,[mH,"Interface ",function(){var a=$APP.u(KG);return $APP.m(a)?$APP.td(a.split(":")):null}()],null),new $APP.V(null,2,5,$APP.W,[OG,vG],null)],null),new $APP.V(null,4,5,$APP.W,[nH,new $APP.V(null,2,5,$APP.W,[oH,new $APP.V(null,2,5,$APP.W,[gH,vG],null)],null),new $APP.V(null,2,5,$APP.W,[pH,"Interface properties"],null),new $APP.V(null,2,5,$APP.W,[$G,vG],null)],null)],null)},uH=function(){return new $APP.V(null,5,5,$APP.W,[$APP.lv,new $APP.V(null,
4,5,$APP.W,[rH,new $APP.V(null,3,5,$APP.W,[sH,new $APP.V(null,2,5,$APP.W,[$APP.my,"Libraries"],null),$APP.m($APP.u(tH))?new $APP.V(null,3,5,$APP.W,[$APP.ey,new $APP.l(null,1,[$APP.Yv,"saving changes"],null),new $APP.V(null,1,5,$APP.W,[$APP.OA],null)],null):new $APP.V(null,3,5,$APP.W,[$APP.Mv,new $APP.l(null,1,[$APP.Yv,"changes saved"],null),new $APP.V(null,1,5,$APP.W,[$APP.PA],null)],null)],null),new $APP.V(null,1,5,$APP.W,[EG],null),new $APP.V(null,1,5,$APP.W,[SG],null)],null),new $APP.V(null,1,
5,$APP.W,[qH],null),new $APP.V(null,1,5,$APP.W,[pG],null),new $APP.V(null,1,5,$APP.W,[jG],null)],null)},wH=function(){if($APP.D(GG)){var a=vH.sync(GG,{live:!0});a.on("paused",function(){return $APP.pf(tH,!1)});a.on("active",function(){return $APP.pf(tH,!0)});a.on("denied",function(){return sG(["Permission denied synchronising to ",$APP.r.g(GG),", changes are saved locally"].join(""))});a.on("error",function(){return sG(["Error synchronising to ",$APP.r.g(GG),", changes are saved locally"].join(""))})}},
xH=function(){window.name="libman";document.onclick=function(){return $APP.Y.s(kG,$APP.X,lG,null)};localStorage.setItem("db",FG);$APP.D(GG)&&localStorage.setItem("sync",GG);wH();return $APP.Dl(new $APP.V(null,1,5,$APP.W,[uH],null),document.getElementById("mosaic_libman"))},IG=function IG(a){switch(arguments.length){case 3:return IG.i(arguments[0],arguments[1],arguments[2]);case 4:return IG.s(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return IG.H(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4]);case 6:return IG.ha(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=new $APP.C(c.slice(6),0,null);return IG.j(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],c)}};
IG.i=function(a,b,c){var d=$APP.D(b);b=$APP.E(d);if(d=$APP.F(d))a=$APP.X.i(a,b,IG.i($APP.O.h(a,b),d,c));else{d=$APP.X.i;var e=$APP.O.h(a,b);c=c.g?c.g(e):c.call(null,e);a=d.call($APP.X,a,b,c)}return a};IG.s=function(a,b,c,d){var e=$APP.D(b);b=$APP.E(e);if(e=$APP.F(e))a=$APP.X.i(a,b,IG.s($APP.O.h(a,b),e,c,d));else{e=$APP.X.i;var f=$APP.O.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);a=e.call($APP.X,a,b,c)}return a};
IG.H=function(a,b,c,d,e){var f=$APP.D(b);b=$APP.E(f);if(f=$APP.F(f))a=$APP.X.i(a,b,IG.H($APP.O.h(a,b),f,c,d,e));else{f=$APP.X.i;var g=$APP.O.h(a,b);c=c.i?c.i(g,d,e):c.call(null,g,d,e);a=f.call($APP.X,a,b,c)}return a};IG.ha=function(a,b,c,d,e,f){var g=$APP.D(b);b=$APP.E(g);if(g=$APP.F(g))a=$APP.X.i(a,b,IG.ha($APP.O.h(a,b),g,c,d,e,f));else{g=$APP.X.i;var h=$APP.O.h(a,b);c=c.s?c.s(h,d,e,f):c.call(null,h,d,e,f);a=g.call($APP.X,a,b,c)}return a};
IG.j=function(a,b,c,d,e,f,g){var h=$APP.D(b);b=$APP.E(h);return(h=$APP.F(h))?$APP.X.i(a,b,$APP.S.j(IG,$APP.O.h(a,b),h,c,d,$APP.J([e,f,g]))):$APP.X.i(a,b,$APP.S.j(c,$APP.O.h(a,b),d,e,f,$APP.J([g])))};IG.C=function(a){var b=$APP.E(a),c=$APP.F(a);a=$APP.E(c);var d=$APP.F(c);c=$APP.E(d);var e=$APP.F(d);d=$APP.E(e);var f=$APP.F(e);e=$APP.E(f);var g=$APP.F(f);f=$APP.E(g);g=$APP.F(g);return this.j(b,a,c,d,e,f,g)};IG.B=6;
var TG=new $APP.P(null,"table","table",-564943036),oG=new $APP.P(null,"left","left",-399115937),jH=new $APP.P(null,"disabled","disabled",-1529784218),uG=new $APP.P(null,"li","li",723558921),rH=new $APP.P(null,"div.libraries","div.libraries",704668226),nH=new $APP.P(null,"div.proppane","div.proppane",-1332639267),bH=new $APP.P(null,"placeholder","placeholder",-104873083),PG=new $APP.P(null,"div.dbprops","div.dbprops",-1556934616),tG=new $APP.P(null,"ul","ul",-1349521403),dH=new $APP.P(null,"decltempl",
"decltempl",-878889161),sH=new $APP.P(null,"div.libhead","div.libhead",1365032704),VG=new $APP.P(null,"tr","tr",-1424774646),WG=new $APP.P(null,"td","td",1479933353),qG=new $APP.P(null,"div","div",1057191632),lH=new $APP.P(null,"summary.button","summary.button",-1314921300),nG=new $APP.P(null,"top","top",-1856271961),QG=new $APP.P(null,"form.properties","form.properties",-224476671),oH=new $APP.P(null,"div.preview","div.preview",-1882273840),yH=new $APP.P(null,"open","open",-1763596448),mG=new $APP.P(null,
"div.contextmenu.window","div.contextmenu.window",729411641),yG=new $APP.P(null,"categories","categories",178386610),fH=new $APP.P(null,"component","component",1555936782),cH=new $APP.P(null,"reftempl","reftempl",2007300758),kH=new $APP.P(null,"div.buttongroup.primary","div.buttongroup.primary",1038300842),RG=new $APP.P(null,"button.primary","button.primary",-486456892),hH=new $APP.P(null,"div.schsel","div.schsel",-1209283060),UG=new $APP.P(null,"tbody","tbody",-80678300),hG=new $APP.P(null,"div.modal.window",
"div.modal.window",-1398751510),eH=new $APP.P(null,"vectors","vectors",-1408542231),DG=new $APP.P(null,"div.empty","div.empty",47401225),BG=new $APP.P(null,"div.cellsel","div.cellsel",-277762551),LG=new $APP.P(null,"div.schematics","div.schematics",908542795),zH=new $APP.P(null,"div.detailbody","div.detailbody",-1679946259),AH=new $APP.P(null,"on-toggle","on-toggle",-695538774),lG=new $APP.P(null,"body","body",-2049205669),iH=new $APP.P(null,"div.addbuttons","div.addbuttons",-579122699),mH=new $APP.P(null,
"h2","h2",-372662728),pH=new $APP.P(null,"h3","h3",2067611163),BH=new $APP.P(null,"details.tree","details.tree",-1643409151);var CH=new URLSearchParams(window.location.search),FG;var DH=CH.get("db");if($APP.m(DH))FG=DH;else{var EH=localStorage.getItem("db");FG=$APP.m(EH)?EH:"schematics"}var FH=$APP.m(window.dburl)?(new URL(FG,window.dburl)).href:FG,GG;var GH=CH.get("sync");if($APP.m(GH))GG=GH;else{var HH=localStorage.getItem("sync");GG=$APP.m(HH)?HH:window.default_sync}var vH=new $APP.Uy(FH),vG=$APP.Km(vH,"models",$APP.xl($APP.U)),IH=$APP.Km(vH,"snapshots",$APP.xl($APP.U));$APP.Im(vH,$APP.J([vG,IH]));
var NG=$APP.xl($APP.Vf),KG=$APP.xl(null),MG=$APP.xl(null),tH=$APP.xl(!1),iG=$APP.xl(null),kG=$APP.xl(new $APP.l(null,3,[$APP.tx,0,$APP.sx,0,lG,null],null)),CG=function CG(a,b){return new $APP.V(null,3,5,$APP.W,[$APP.lv,$APP.Sh(function(){return function f(e){return new $APP.Ce(null,function(){for(var g=e;;){var h=$APP.D(g);if(h){var n=h;if($APP.Kd(n)){var p=$APP.uc(n),q=$APP.H(p),t=$APP.Fe(q);return function(){for(var G=0;;)if(G<q){var K=$APP.wd(p,G),M=$APP.N(K,0,null),Q=$APP.N(K,1,null);if($APP.D(M)&&
$APP.D(Q)){var T=$APP.ue.h(a,M);$APP.Je(t,new $APP.V(null,4,5,$APP.W,[BH,new $APP.l(null,4,[$APP.wj,T,$APP.pl,T,yH,xG($APP.u(NG),T),AH,function(ba,Z,ca){return function(sa){return $APP.m(sa.target.open)?(sa.stopPropagation(),$APP.pf(KG,null),$APP.pf(MG,null),$APP.pf(NG,ca)):null}}(G,g,T,K,M,Q,p,q,t,n,h)],null),new $APP.V(null,2,5,$APP.W,[$APP.vw,M],null),new $APP.V(null,2,5,$APP.W,[zH,new $APP.V(null,3,5,$APP.W,[CG,T,Q],null)],null)],null))}G+=1}else return!0}()?$APP.Ie($APP.Ke(t),f($APP.vc(n))):
$APP.Ie($APP.Ke(t),null)}var w=$APP.E(n),y=$APP.N(w,0,null),A=$APP.N(w,1,null);if($APP.D(y)&&$APP.D(A)){var B=$APP.ue.h(a,y);return $APP.xe(new $APP.V(null,4,5,$APP.W,[BH,new $APP.l(null,4,[$APP.wj,B,$APP.pl,B,yH,xG($APP.u(NG),B),AH,function(G,K){return function(M){return $APP.m(M.target.open)?(M.stopPropagation(),$APP.pf(KG,null),$APP.pf(MG,null),$APP.pf(NG,K)):null}}(g,B,w,y,A,n,h)],null),new $APP.V(null,2,5,$APP.W,[$APP.vw,y],null),new $APP.V(null,2,5,$APP.W,[zH,new $APP.V(null,3,5,$APP.W,[CG,
B,A],null)],null)],null),f($APP.Uc(n)))}g=$APP.Uc(n)}else return null}},null,null)}(b)}()),new $APP.V(null,5,5,$APP.W,[$APP.SA,KG,$APP.Sh(function(){return function f(e){return new $APP.Ce(null,function(){for(var g=e;;)if(g=$APP.D(g)){if($APP.Kd(g)){var h=$APP.uc(g),n=$APP.H(h),p=$APP.Fe(n);a:for(var q=0;;)if(q<n){var t=$APP.wd(h,q),w=$APP.N(t,0,null);t=$APP.N(t,1,null);if($APP.Cd(t)){t=$APP.O.h($APP.u(vG),w);var y=$APP.td(w.split(":"));w=new $APP.V(null,4,5,$APP.W,[$APP.O.i(t,$APP.tj,y),new $APP.V(null,
2,5,$APP.W,[gG,$APP.yl(vG,new $APP.V(null,2,5,$APP.W,[w,$APP.tj],null))],null),w,y],null);p.add(w)}q+=1}else{h=!0;break a}return h?$APP.Ie($APP.Ke(p),f($APP.vc(g))):$APP.Ie($APP.Ke(p),null)}h=$APP.E(g);p=$APP.N(h,0,null);h=$APP.N(h,1,null);if($APP.Cd(h))return h=$APP.O.h($APP.u(vG),p),n=$APP.td(p.split(":")),$APP.xe(new $APP.V(null,4,5,$APP.W,[$APP.O.i(h,$APP.tj,n),new $APP.V(null,2,5,$APP.W,[gG,$APP.yl(vG,new $APP.V(null,2,5,$APP.W,[p,$APP.tj],null))],null),p,n],null),f($APP.Uc(g)));g=$APP.Uc(g)}else return null},
null,null)}(b)}()),null,function(d){return function(e){return wG(e,d)}}],null)],null)},aH=$APP.xl("NgSpice");$APP.qa("nyancad.mosaic.libman.init",xH);try{xH()}catch(a){throw console.error("An error occurred when calling (nyancad.mosaic.libman/init)"),a;};
}).call(this);