(function(){
'use strict';var dy=function(a){for(var b=Array(arguments.length),c=0;;)if(c<b.length)b[c]=arguments[c],c+=1;else return b},ey=function(a){a=a.destroy;return null==a?null:a.m?a.m():a.call(null)},fy=function(){var a=$APP.tj;return null==a?[]:$APP.Ej(dy,a,$APP.Yr,null,ey)},gy=function(a,b,c){for(var d=0,e=$APP.G(a);;)if(d<e){var f=$APP.Zd(d+e);var g=$APP.P.h(a,f);g=c.g?c.g(g):c.call(null,g);0>$APP.Fd(g,b)?d=f+1:e=f}else return d},hy=function(a,b,c){return $APP.Gf($APP.hf.l($APP.Nf(a,0,b),new $APP.T(null,
1,5,$APP.V,[c],null),$APP.N([$APP.Nf(a,b,$APP.G(a))])))},iy=function(a,b){return $APP.Gf($APP.hf.h($APP.Nf(a,0,b),$APP.Nf(a,b+1,$APP.G(a))))},jy=function(a,b){function c(g){return $APP.Nf(g,0,2)}a=$APP.Gf(a);var d=c(b),e=gy(a,d,c),f=$APP.P.h(a,e);return $APP.wd(f)&&$APP.H.h(d,c(f))?$APP.X.i(a,e,b):hy(a,e,b)},ky=function(a,b){function c(f){return $APP.Nf(f,0,2)}a=$APP.Gf(a);b=c(b);var d=gy(a,b,c),e=$APP.P.h(a,d);$APP.Wh($APP.N([a,b,d,e]));return $APP.wd(e)&&$APP.H.h(b,c(e))?iy(a,d):a},ly=function(a,
b){function c(e){return $APP.Nf(e,0,2)}a=$APP.Gf(a);b=c(b);var d=gy(a,b,c);a=$APP.P.h(a,d);return $APP.wd(a)&&$APP.H.h(b,c(a))},my=function(a){var b=fy(),c=0===b.length,d=c||$APP.La(b.hasOwnProperty(0))?b[0]=$APP.Tj.g(!1):b[0],e=c||$APP.La(b.hasOwnProperty(1))?b[1]=$APP.$e(null):b[1],f=c||$APP.La(b.hasOwnProperty(2))?b[2]=function(){return $APP.af(d,!0)}:b[2];return $APP.q(function(){var g=$APP.y(d);return $APP.q(g)?g:$APP.qd($APP.y(a))}())?new $APP.T(null,3,5,$APP.V,[$APP.vq,new $APP.n(null,1,[$APP.Fq,
function(g){console.log(g);g.preventDefault();$APP.af(a,g.target.elements.namefield.value);return $APP.af(d,!1)}],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,5,[$APP.Xp,$APP.Dq,$APP.bj,"namefield",$APP.Iq,!0,$APP.Rp,$APP.y(a),$APP.mr,function(g){$APP.af(a,g.target.value);return $APP.af(d,!1)}],null)],null)],null):new $APP.T(null,3,5,$APP.V,[$APP.aq,new $APP.n(null,1,[$APP.Bp,function(g){return $APP.H.h(g.detail,1)?$APP.af(e,window.setTimeout(f,1E3)):window.clearTimeout($APP.y(e))}],
null),$APP.y(a)],null)},sy=function(a){var b=$APP.P.h($APP.y(ny),a);if($APP.q(b))var c=b;else{b=$APP.P.i($APP.y(oy),a,py);c=$APP.bj.g(b);c=$APP.q(window.dburl)?(new URL(c,window.dburl)).href:c;var d=new $APP.fs(c);c=$APP.km(d,"models",$APP.al(qy,new $APP.T(null,1,5,$APP.V,[a],null)));$APP.im(d,$APP.N([c]));$APP.q(ry.g(b))&&$APP.fs.sync(ry.g(b),d);$APP.Y.u(ny,$APP.X,a,c)}return c},Cy=function(){return new $APP.T(null,2,5,$APP.V,[ty,$APP.Ch(function(){return function c(b){return new $APP.le(null,function(){for(;;){var d=
$APP.D(b);if(d){var e=d;if($APP.xd(e)){var f=$APP.lc(e),g=$APP.G(f),h=$APP.pe(g);return function(){for(var t=0;;)if(t<g){var x=$APP.kd(f,t),w=$APP.O(x,0,null),v=$APP.O(x,1,null),z=sy(w);$APP.te(h,new $APP.T(null,4,5,$APP.V,[uy,new $APP.n(null,3,[$APP.ej,w,vy,$APP.H.h(w,$APP.y(wy)),xy,function(I,J,M,R){return function(ba){return $APP.q(ba.target.open)?$APP.af(wy,R):null}}(t,z,x,w,v,f,g,h,e,d)],null),new $APP.T(null,2,5,$APP.V,[yy,$APP.bj.g(v)],null),new $APP.T(null,2,5,$APP.V,[zy,new $APP.T(null,3,
5,$APP.V,[$APP.tt,Ay,function(){return function(I,J,M,R,ba,U,W,pa,Z,oa){return function ib(Ua){return new $APP.le(null,function(Fb,Pb){return function(){for(;;){var ic=$APP.D(Ua);if(ic){if($APP.xd(ic)){var cb=$APP.lc(ic),$b=$APP.G(cb),ac=$APP.pe($b);a:for(var id=0;;)if(id<$b){var Gb=$APP.kd(cb,id),jd=$APP.O(Gb,0,null);Gb=$APP.O(Gb,1,null);var Ke=$APP.fd(jd.split(":"));jd=new $APP.T(null,4,5,$APP.V,[$APP.P.i(Gb,$APP.bj,Ke),new $APP.T(null,2,5,$APP.V,[my,$APP.al(Pb,new $APP.T(null,2,5,$APP.V,[jd,$APP.bj],
null))],null),jd,Ke],null);ac.add(jd);id+=1}else{cb=!0;break a}return cb?$APP.se($APP.ue(ac),ib($APP.mc(ic))):$APP.se($APP.ue(ac),null)}cb=$APP.E(ic);ac=$APP.O(cb,0,null);cb=$APP.O(cb,1,null);$b=$APP.fd(ac.split(":"));return $APP.Q(new $APP.T(null,4,5,$APP.V,[$APP.P.i(cb,$APP.bj,$b),new $APP.T(null,2,5,$APP.V,[my,$APP.al(Pb,new $APP.T(null,2,5,$APP.V,[ac,$APP.bj],null))],null),ac,$b],null),ib($APP.Jc(ic)))}return null}}}(I,J,M,R,ba,U,W,pa,Z,oa),null,null)}}(t,z,x,w,v,f,g,h,e,d)($APP.y(z))}()],null)],
null)],null));t+=1}else return!0}()?$APP.se($APP.ue(h),c($APP.mc(e))):$APP.se($APP.ue(h),null)}var l=$APP.E(e),m=$APP.O(l,0,null),p=$APP.O(l,1,null),r=sy(m);return $APP.Q(new $APP.T(null,4,5,$APP.V,[uy,new $APP.n(null,3,[$APP.ej,m,vy,$APP.H.h(m,$APP.y(wy)),xy,function(t,x,w){return function(v){return $APP.q(v.target.open)?$APP.af(wy,w):null}}(r,l,m,p,e,d)],null),new $APP.T(null,2,5,$APP.V,[yy,$APP.bj.g(p)],null),new $APP.T(null,2,5,$APP.V,[zy,new $APP.T(null,3,5,$APP.V,[$APP.tt,Ay,function(){return function(t){return function v(w){return new $APP.le(null,
function(){for(;;){var z=$APP.D(w);if(z){if($APP.xd(z)){var I=$APP.lc(z),J=$APP.G(I),M=$APP.pe(J);a:for(var R=0;;)if(R<J){var ba=$APP.kd(I,R),U=$APP.O(ba,0,null);ba=$APP.O(ba,1,null);var W=$APP.fd(U.split(":"));U=new $APP.T(null,4,5,$APP.V,[$APP.P.i(ba,$APP.bj,W),new $APP.T(null,2,5,$APP.V,[my,$APP.al(t,new $APP.T(null,2,5,$APP.V,[U,$APP.bj],null))],null),U,W],null);M.add(U);R+=1}else{I=!0;break a}return I?$APP.se($APP.ue(M),v($APP.mc(z))):$APP.se($APP.ue(M),null)}I=$APP.E(z);M=$APP.O(I,0,null);I=
$APP.O(I,1,null);J=$APP.fd(M.split(":"));return $APP.Q(new $APP.T(null,4,5,$APP.V,[$APP.P.i(I,$APP.bj,J),new $APP.T(null,2,5,$APP.V,[my,$APP.al(t,new $APP.T(null,2,5,$APP.V,[M,$APP.bj],null))],null),M,J],null),v($APP.Jc(z)))}return null}},null,null)}}(r,l,m,p,e,d)($APP.y(r))}()],null)],null)],null),c($APP.Jc(e)))}return null}},null,null)}($APP.hf.h(new $APP.T(null,1,5,$APP.V,[new $APP.T(null,2,5,$APP.V,[By,py],null)],null),$APP.y(oy)))}())],null)},Fy=function(a){var b=$APP.y(Ay),c=$APP.P.h($APP.y(a),
b);return new $APP.T(null,2,5,$APP.V,[Dy,new $APP.T(null,4,5,$APP.V,[$APP.tt,Ey,function(){return function f(e){return new $APP.le(null,function(){for(;;){var g=$APP.D(e);if(g){if($APP.xd(g)){var h=$APP.lc(g),l=$APP.G(h),m=$APP.pe(l);a:for(var p=0;;)if(p<l){var r=$APP.kd(h,p),t=$APP.O(r,0,null);r=$APP.O(r,1,null);t=new $APP.T(null,4,5,$APP.V,[$APP.P.i(r,$APP.bj,t),new $APP.T(null,2,5,$APP.V,[my,$APP.al(a,new $APP.T(null,4,5,$APP.V,[b,$APP.Pr,t,$APP.bj],null))],null),t,t],null);m.add(t);p+=1}else{h=
!0;break a}return h?$APP.se($APP.ue(m),f($APP.mc(g))):$APP.se($APP.ue(m),null)}h=$APP.E(g);m=$APP.O(h,0,null);h=$APP.O(h,1,null);return $APP.Q(new $APP.T(null,4,5,$APP.V,[$APP.P.i(h,$APP.bj,m),new $APP.T(null,2,5,$APP.V,[my,$APP.al(a,new $APP.T(null,4,5,$APP.V,[b,$APP.Pr,m,$APP.bj],null))],null),m,m],null),f($APP.Jc(g)))}return null}},null,null)}($APP.Pr.g(c))}(),function(d){$APP.Wh($APP.N([c,d]));return $APP.H.h($APP.mf(c,new $APP.T(null,3,5,$APP.V,[$APP.Pr,d,$APP.Xp],null)),"schematic")?function(){var e=
window,f=e.open,g=$APP.fd(b.split(":")),h=$APP.uh(d);g=[$APP.u.g(g),"$",$APP.u.g(h)].join("");h=$APP.P.i($APP.y(oy),$APP.y(wy),py);var l=new URL("editor",window.location);l.searchParams.append("schem",g);l.searchParams.append("db",$APP.bj.h(h,""));l.searchParams.append("sync",ry.h(h,""));return f.call(e,l,b)}:null}],null)],null)},Iy=function(){var a=$APP.y(wy),b=$APP.P.i($APP.y(oy),a,py);return $APP.q(a)?new $APP.T(null,3,5,$APP.V,[Gy,new $APP.T(null,2,5,$APP.V,[Hy,"Library properties"],null),new $APP.T(null,
5,5,$APP.V,[$APP.xp,new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,1,[$APP.Tp,"dbname"],null),"Name"],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Vk,"dbname",$APP.jr,$APP.bj.g(b),$APP.pp,function(c){return $APP.Y.u(oy,$APP.Vo,new $APP.T(null,2,5,$APP.V,[a,$APP.bj],null),c.target.value)}],null)],null),new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,1,[$APP.Tp,"dburl"],null),"URL"],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Vk,"dburl",$APP.jr,ry.g(b),
$APP.pp,function(c){return $APP.Y.u(oy,$APP.Vo,new $APP.T(null,2,5,$APP.V,[a,ry],null),c.target.value)}],null)],null)],null)],null):null},Ny=function(a){$APP.Wh($APP.N([$APP.y(a)]));var b=$APP.Br.g($APP.y(a)),c=$APP.O(b,0,null),d=$APP.O(b,1,null),e=2+c,f=2+d;$APP.Wh($APP.N([e,f]));return new $APP.T(null,2,5,$APP.V,[Jy,new $APP.T(null,2,5,$APP.V,[Ky,$APP.Ch(function(){return function l(h){return new $APP.le(null,function(){for(;;){var m=$APP.D(h);if(m){var p=m;if($APP.xd(p)){var r=$APP.lc(p),t=$APP.G(r),
x=$APP.pe(t);return function(){for(var v=0;;)if(v<t){var z=$APP.kd(r,v);$APP.te(x,new $APP.T(null,3,5,$APP.V,[Ly,new $APP.n(null,1,[$APP.ej,z],null),$APP.Ch(function(){return function(I,J,M,R,ba,U,W,pa,Z,oa,ya,Ua){return function Pb(Fb){return new $APP.le(null,function(ic,cb,$b,ac,id,Gb,jd,Ke,Mg,eg,fg,Le){return function(){for(;;){var Td=$APP.D(Fb);if(Td){var Ud=Td;if($APP.xd(Ud)){var rf=$APP.lc(Ud),Ri=$APP.G(rf),Ng=$APP.pe(Ri);return function(){for(var Og=0;;)if(Og<Ri){var gg=$APP.kd(rf,Og),Si=function(Ti,
Ui,Eb,lz,mz,nz,oz,pz,gt){return function(Ty){return $APP.q(Ty.target.checked)?$APP.Y.l(a,$APP.Wo,$APP.Wp,jy,$APP.N([new $APP.T(null,3,5,$APP.V,[Eb,gt,"#"],null)])):$APP.Y.l(a,$APP.Wo,$APP.Wp,ky,$APP.N([new $APP.T(null,3,5,$APP.V,[Eb,gt,"#"],null)]))}}(Og,ic,gg,rf,Ri,Ng,Ud,Td,cb,$b,ac,id,Gb,jd,Ke,Mg,eg,fg,Le);$APP.te(Ng,new $APP.T(null,3,5,$APP.V,[My,new $APP.n(null,1,[$APP.ej,gg],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Xp,"checkbox",$APP.Sq,ly($APP.Wp.g($APP.y(a)),new $APP.T(null,
2,5,$APP.V,[gg,cb],null)),$APP.pp,Si],null)],null)],null));Og+=1}else return!0}()?$APP.se($APP.ue(Ng),Pb($APP.mc(Ud))):$APP.se($APP.ue(Ng),null)}var ne=$APP.E(Ud),Ik=function(Og,gg,Si,Ti,Ui){return function(Eb){return $APP.q(Eb.target.checked)?$APP.Y.l(a,$APP.Wo,$APP.Wp,jy,$APP.N([new $APP.T(null,3,5,$APP.V,[gg,Ui,"#"],null)])):$APP.Y.l(a,$APP.Wo,$APP.Wp,ky,$APP.N([new $APP.T(null,3,5,$APP.V,[gg,Ui,"#"],null)]))}}(ic,ne,Ud,Td,cb,$b,ac,id,Gb,jd,Ke,Mg,eg,fg,Le);return $APP.Q(new $APP.T(null,3,5,$APP.V,
[My,new $APP.n(null,1,[$APP.ej,ne],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Xp,"checkbox",$APP.Sq,ly($APP.Wp.g($APP.y(a)),new $APP.T(null,2,5,$APP.V,[ne,cb],null)),$APP.pp,Ik],null)],null)],null),Pb($APP.Jc(Ud)))}return null}}}(I,J,M,R,ba,U,W,pa,Z,oa,ya,Ua),null,null)}}(v,z,r,t,x,p,m,b,c,d,e,f)($APP.Ah(e))}())],null));v+=1}else return!0}()?$APP.se($APP.ue(x),l($APP.mc(p))):$APP.se($APP.ue(x),null)}var w=$APP.E(p);return $APP.Q(new $APP.T(null,3,5,$APP.V,[Ly,new $APP.n(null,
1,[$APP.ej,w],null),$APP.Ch(function(){return function(v,z,I,J,M,R,ba,U){return function Z(pa){return new $APP.le(null,function(){for(;;){var oa=$APP.D(pa);if(oa){var ya=oa;if($APP.xd(ya)){var Ua=$APP.lc(ya),ib=$APP.G(Ua),Fb=$APP.pe(ib);return function(){for(var cb=0;;)if(cb<ib){var $b=$APP.kd(Ua,cb),ac=function(id,Gb,jd,Ke,Mg,eg,fg,Le){return function(Td){return $APP.q(Td.target.checked)?$APP.Y.l(a,$APP.Wo,$APP.Wp,jy,$APP.N([new $APP.T(null,3,5,$APP.V,[Gb,Le,"#"],null)])):$APP.Y.l(a,$APP.Wo,$APP.Wp,
ky,$APP.N([new $APP.T(null,3,5,$APP.V,[Gb,Le,"#"],null)]))}}(cb,$b,Ua,ib,Fb,ya,oa,v,z,I,J,M,R,ba,U);$APP.te(Fb,new $APP.T(null,3,5,$APP.V,[My,new $APP.n(null,1,[$APP.ej,$b],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Xp,"checkbox",$APP.Sq,ly($APP.Wp.g($APP.y(a)),new $APP.T(null,2,5,$APP.V,[$b,v],null)),$APP.pp,ac],null)],null)],null));cb+=1}else return!0}()?$APP.se($APP.ue(Fb),Z($APP.mc(ya))):$APP.se($APP.ue(Fb),null)}var Pb=$APP.E(ya),ic=function(cb,$b,ac,id){return function(Gb){return $APP.q(Gb.target.checked)?
$APP.Y.l(a,$APP.Wo,$APP.Wp,jy,$APP.N([new $APP.T(null,3,5,$APP.V,[cb,id,"#"],null)])):$APP.Y.l(a,$APP.Wo,$APP.Wp,ky,$APP.N([new $APP.T(null,3,5,$APP.V,[cb,id,"#"],null)]))}}(Pb,ya,oa,v,z,I,J,M,R,ba,U);return $APP.Q(new $APP.T(null,3,5,$APP.V,[My,new $APP.n(null,1,[$APP.ej,Pb],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,3,[$APP.Xp,"checkbox",$APP.Sq,ly($APP.Wp.g($APP.y(a)),new $APP.T(null,2,5,$APP.V,[Pb,v],null)),$APP.pp,ic],null)],null)],null),Z($APP.Jc(ya)))}return null}},null,null)}}(w,
p,m,b,c,d,e,f)($APP.Ah(e))}())],null),l($APP.Jc(p)))}return null}},null,null)}($APP.Ah(f))}())],null)],null)},Oy=function(a){$APP.Wh($APP.N([$APP.y(a)]));return new $APP.T(null,5,5,$APP.V,[$APP.Jp,new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,2,[$APP.Tp,"bgwidth",$APP.iq,"Width of the background tile"],null),"Background width"],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,4,[$APP.Vk,"bgwidth",$APP.Xp,"number",$APP.Rp,$APP.P.i($APP.Br.g($APP.y(a)),0,1),$APP.pp,$APP.la(function(b){return $APP.Y.l(a,
$APP.Wo,$APP.Br,$APP.Ve($APP.X,new $APP.T(null,2,5,$APP.V,[0,0],null)),$APP.N([0,parseInt(b.target.value)]))})],null)],null),new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,2,[$APP.Tp,"bgheight",$APP.iq,"Width of the background tile"],null),"Background height"],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,4,[$APP.Vk,"bgheigt",$APP.Xp,"number",$APP.Rp,$APP.P.i($APP.Br.g($APP.y(a)),1,1),$APP.pp,$APP.la(function(b){return $APP.Y.l(a,$APP.Wo,$APP.Br,$APP.Ve($APP.X,new $APP.T(null,2,5,
$APP.V,[0,0],null)),$APP.N([1,parseInt(b.target.value)]))})],null)],null)],null)},Py=function(a){return new $APP.T(null,2,5,$APP.V,[$APP.Jp,function(){return function d(c){return new $APP.le(null,function(){for(;;){var e=$APP.D(c);if(e){var f=e;if($APP.xd(f)){var g=$APP.lc(f),h=$APP.G(g),l=$APP.pe(h);return function(){for(var x=0;;)if(x<h){var w=$APP.kd(g,x),v=$APP.O(w,0,null),z=$APP.O(w,1,null),I=$APP.O(w,2,null);w=$APP.la(function(J,M,R,ba){return function(U){return $APP.Y.l(a,$APP.Wo,$APP.Wp,jy,
$APP.N([new $APP.T(null,3,5,$APP.V,[R,ba,U.target.value],null)]))}}(x,w,v,z,I,g,h,l,f,e));$APP.te(l,new $APP.T(null,4,5,$APP.V,[$APP.Jp,new $APP.n(null,1,[$APP.ej,new $APP.T(null,2,5,$APP.V,[v,z],null)],null),new $APP.T(null,5,5,$APP.V,[$APP.Rq,new $APP.n(null,2,[$APP.Tp,["port",$APP.u.g(v),":",$APP.u.g(z)].join(""),$APP.iq,"Port name"],null),v,"/",z],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,4,[$APP.Vk,["port",$APP.u.g(v),":",$APP.u.g(z)].join(""),$APP.Xp,"text",$APP.Rp,I,$APP.pp,
w],null)],null)],null));x+=1}else return!0}()?$APP.se($APP.ue(l),d($APP.mc(f))):$APP.se($APP.ue(l),null)}var m=$APP.E(f),p=$APP.O(m,0,null),r=$APP.O(m,1,null),t=$APP.O(m,2,null);m=$APP.la(function(x,w,v){return function(z){return $APP.Y.l(a,$APP.Wo,$APP.Wp,jy,$APP.N([new $APP.T(null,3,5,$APP.V,[w,v,z.target.value],null)]))}}(m,p,r,t,f,e));return $APP.Q(new $APP.T(null,4,5,$APP.V,[$APP.Jp,new $APP.n(null,1,[$APP.ej,new $APP.T(null,2,5,$APP.V,[p,r],null)],null),new $APP.T(null,5,5,$APP.V,[$APP.Rq,new $APP.n(null,
2,[$APP.Tp,["port",$APP.u.g(p),":",$APP.u.g(r)].join(""),$APP.iq,"Port name"],null),p,"/",r],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,4,[$APP.Vk,["port",$APP.u.g(p),":",$APP.u.g(r)].join(""),$APP.Xp,"text",$APP.Rp,t,$APP.pp,m],null)],null)],null),d($APP.Jc(f)))}return null}},null,null)}($APP.Wp.g($APP.y(a)))}()],null)},Qy=function(a){var b=$APP.y(Ay),c=$APP.al(a,new $APP.T(null,1,5,$APP.V,[b],null));return $APP.q(b)?new $APP.T(null,2,5,$APP.V,[$APP.Jp,new $APP.T(null,7,5,$APP.V,[$APP.xp,
new $APP.T(null,2,5,$APP.V,[Oy,c],null),new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,2,[$APP.Tp,"ports",$APP.iq,"pattern for the device ports"],null),"ports"],null),new $APP.T(null,2,5,$APP.V,[Ny,c],null),new $APP.T(null,2,5,$APP.V,[Py,c],null),new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,2,[$APP.Tp,"symurl",$APP.iq,"image url for this component"],null),"url"],null),new $APP.T(null,2,5,$APP.V,[$APP.Pq,new $APP.n(null,4,[$APP.Vk,"symurl",$APP.Xp,"text",$APP.Rp,$APP.mf($APP.y(a),new $APP.T(null,
2,5,$APP.V,[b,$APP.Ur],null)),$APP.mr,function(d){return $APP.Y.u(a,$APP.Vo,new $APP.T(null,2,5,$APP.V,[b,$APP.Ur],null),d.target.value)}],null)],null)],null)],null):null},Vy=function(a){var b=$APP.al(a,new $APP.T(null,3,5,$APP.V,[$APP.y(Ay),$APP.Pr,$APP.Nh.g($APP.y(Ey))],null));$APP.Wh($APP.N([$APP.eh($APP.mf($APP.y(a),new $APP.T(null,2,5,$APP.V,[$APP.y(Ay),$APP.Pr],null)))]));return $APP.H.h($APP.Xp.g($APP.y(b)),"spice")?new $APP.T(null,5,5,$APP.V,[$APP.xp,new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,
1,[$APP.Tp,"reftempl"],null),"Reference template"],null),new $APP.T(null,2,5,$APP.V,[Ry,new $APP.n(null,3,[$APP.Vk,"reftempl",$APP.jr,Sy.h($APP.y(b),"X{name} {ports} {properties}"),$APP.pp,function(c){return $APP.Y.u(b,$APP.X,Sy,c.target.value)}],null)],null),new $APP.T(null,3,5,$APP.V,[$APP.Rq,new $APP.n(null,1,[$APP.Tp,"decltempl"],null),"Declaration template"],null),new $APP.T(null,2,5,$APP.V,[Ry,new $APP.n(null,3,[$APP.Vk,"decltempl",$APP.jr,Uy.g($APP.y(b)),$APP.pp,function(c){return $APP.Y.u(b,
$APP.X,Uy,c.target.value)}],null)],null)],null):"TODO: preview"},fz=function(){var a=sy(function(){var b=$APP.y(wy);return $APP.q(b)?b:By}());return new $APP.T(null,3,5,$APP.V,[$APP.Jp,new $APP.T(null,4,5,$APP.V,[Wy,new $APP.T(null,3,5,$APP.V,[Xy,new $APP.T(null,3,5,$APP.V,[Yy,new $APP.n(null,2,[$APP.Bp,function(){var b=$APP.y(wy);b=$APP.q(b)?prompt("Enter the name of the new cell"):b;return $APP.q(b)?$APP.Y.u(a,$APP.X,["models:",$APP.u.g(b)].join(""),new $APP.n(null,1,[$APP.bj,b],null)):null},Zy,
null==$APP.y(wy)],null),"+ Add cell"],null),new $APP.T(null,3,5,$APP.V,[$y,new $APP.T(null,3,5,$APP.V,[Yy,new $APP.n(null,2,[$APP.Bp,function(){var b=$APP.y(wy);$APP.q(b)&&(b=$APP.y(Ay),b=$APP.q(b)?prompt("Enter the name of the new schematic"):b);return $APP.q(b)?$APP.Y.u(a,$APP.Vo,new $APP.T(null,3,5,$APP.V,[$APP.y(Ay),$APP.Pr,$APP.Nh.g(b)],null),new $APP.n(null,2,[$APP.bj,b,$APP.Xp,"schematic"],null)):null},Zy,null==$APP.y(wy)||null==$APP.y(Ay)],null),"+ Add schematic"],null),new $APP.T(null,3,
5,$APP.V,[az,new $APP.T(null,1,5,$APP.V,[bz],null),new $APP.T(null,3,5,$APP.V,[Yy,new $APP.n(null,2,[$APP.Bp,function(){var b=$APP.y(wy);$APP.q(b)&&(b=$APP.y(Ay),b=$APP.q(b)?prompt("Enter the name of the new SPICE model"):b);return $APP.q(b)?$APP.Y.u(a,$APP.Vo,new $APP.T(null,3,5,$APP.V,[$APP.y(Ay),$APP.Pr,$APP.Nh.g(b)],null),new $APP.n(null,2,[$APP.bj,b,$APP.Xp,"spice"],null)):null},Zy,null==$APP.y(wy)||null==$APP.y(Ay)],null),"+ Add SPICE model"],null)],null)],null)],null),new $APP.T(null,3,5,$APP.V,
[cz,"Cell ",function(){var b=$APP.y(Ay);return $APP.q(b)?$APP.fd(b.split(":")):null}()],null),new $APP.T(null,2,5,$APP.V,[Fy,a],null)],null),new $APP.T(null,3,5,$APP.V,[dz,new $APP.T(null,2,5,$APP.V,[ez,new $APP.T(null,2,5,$APP.V,[Vy,a],null)],null),new $APP.T(null,2,5,$APP.V,[Qy,a],null)],null)],null)},jz=function(){return new $APP.T(null,3,5,$APP.V,[$APP.Jp,new $APP.T(null,4,5,$APP.V,[gz,new $APP.T(null,3,5,$APP.V,[hz,new $APP.T(null,2,5,$APP.V,[$APP.Gr,"Library"],null),new $APP.T(null,3,5,$APP.V,
[iz,new $APP.n(null,1,[$APP.Bp,function(){var a=prompt("Enter the name of the new database");return $APP.D(a)?$APP.Y.u(oy,$APP.X,["databases:",$APP.u.g(a)].join(""),new $APP.n(null,1,[$APP.bj,a],null)):null}],null),"+"],null)],null),new $APP.T(null,1,5,$APP.V,[Cy],null),new $APP.T(null,1,5,$APP.V,[Iy],null)],null),new $APP.T(null,1,5,$APP.V,[fz],null)],null)},kz=function(){window.name="libman";var a=new $APP.T(null,1,5,$APP.V,[jz],null),b=document.getElementById("mosaic_libman");return $APP.gl(a,
b)},Jy=new $APP.S(null,"table","table",-564943036),Zy=new $APP.S(null,"disabled","disabled",-1529784218),gz=new $APP.S(null,"div.libraries","div.libraries",704668226),dz=new $APP.S(null,"div.proppane","div.proppane",-1332639267),Gy=new $APP.S(null,"div.dbprops","div.dbprops",-1556934616),Uy=new $APP.S(null,"decltempl","decltempl",-878889161),hz=new $APP.S(null,"div.libhead","div.libhead",1365032704),Ly=new $APP.S(null,"tr","tr",-1424774646),My=new $APP.S(null,"td","td",1479933353),bz=new $APP.S(null,
"summary.button","summary.button",-1314921300),ez=new $APP.S(null,"div.preview","div.preview",-1882273840),vy=new $APP.S(null,"open","open",-1763596448),yy=new $APP.S(null,"summary","summary",380847952),Sy=new $APP.S(null,"reftempl","reftempl",2007300758),$y=new $APP.S(null,"div.buttongroup.primary","div.buttongroup.primary",1038300842),iz=new $APP.S(null,"button.plus","button.plus",40612401),Wy=new $APP.S(null,"div.schsel","div.schsel",-1209283060),Yy=new $APP.S(null,"button","button",1456579943),
Ky=new $APP.S(null,"tbody","tbody",-80678300),By=new $APP.S(null,"schematics","schematics",912295165),ty=new $APP.S(null,"div.cellsel","div.cellsel",-277762551),Dy=new $APP.S(null,"div.schematics","div.schematics",908542795),zy=new $APP.S(null,"div.detailbody","div.detailbody",-1679946259),az=new $APP.S(null,"details","details",1956795411),xy=new $APP.S(null,"on-toggle","on-toggle",-695538774),ry=new $APP.S(null,"url","url",276297046),Xy=new $APP.S(null,"div.addbuttons","div.addbuttons",-579122699),
cz=new $APP.S(null,"h2","h2",-372662728),Hy=new $APP.S(null,"h3","h3",2067611163),Ry=new $APP.S(null,"textarea","textarea",-650375824),uy=new $APP.S(null,"details.tree","details.tree",-1643409151);var wy=$APP.Tj.g(null),Ay=$APP.Tj.g(null),Ey=$APP.Tj.g(null),oy=$APP.km(new $APP.fs("local"),"databases",$APP.Tj.g($APP.Me)),qy=$APP.Tj.g($APP.Me),ny=$APP.$e($APP.Me),py=new $APP.n(null,2,[$APP.bj,"schematics",ry,"https://c6be5bcc-59a8-492d-91fd-59acc17fef02-bluemix.cloudantnosqldb.appdomain.cloud/schematics"],null);$APP.ka("nyancad.mosaic.libman.init",kz);try{kz()}catch(a){throw console.error("An error occurred when calling (nyancad.mosaic.libman/init)"),a;};
}).call(this);